server.port=8081

spring.application.name=servicio-ligas

spring.datasource.url=jdbc:mysql://localhost:3306/bd_ligas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=system


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=system-system-system-system-system-1234

# Documentacion Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


# 3. URL donde está publicado tu Servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 4. Indica que este microservicio se debe registrar en Eureka al iniciar
eureka.client.register-with-eureka=true

# 5. Permite al microservicio consultar el directorio de Eureka
eureka.client.fetch-registry=true

# 6. Registra preferentemente la IP del servicio en lugar del hostname (evita problemas de red local)
eureka.instance.prefer-ip-address=true