server.port=8090
spring.application.name=servicio-auth

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

usuarios.url=http://servicio-usuarios:8091

jwt.secret=system-system-system-system-system-1234

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

eureka.client.service-url.defaultZone=http://servidor-eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true