server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # 1. Microservicio Auth
            - id: auth-service
              uri: lb://servicio-auth
              predicates:
                - Path=/api/auth/**

            # 2. Microservicio Países
            - id: paises-service
              uri: lb://servicio-paises
              predicates:
                - Path=/api/paises/**

            # 3. Microservicio Clubes
            - id: clubes-service
              uri: lb://servicio-clubes
              predicates:
                - Path=/api/clubes/**

            # 4. Microservicio Estadios
            - id: estadios-service
              uri: lb://servicio-estadios
              predicates:
                - Path=/api/estadios/**

            # 5. Microservicio Entrenadores
            - id: entrenadores-service
              uri: lb://servicio-entrenadores
              predicates:
                - Path=/api/entrenadores/**

            # 6. Microservicio Lesiones
            - id: lesiones-service
              uri: lb://servicio-lesiones
              predicates:
                - Path=/api/lesiones/**

            # 7. Microservicio Ligas
            - id: ligas-service
              uri: lb://servicio-ligas
              predicates:
                - Path=/api/ligas/**

            # 8. Microservicio Jugadores
            - id: jugadores-service
              uri: lb://servicio-jugadores
              predicates:
                - Path=/api/jugadores/**

            # 9. Microservicio Football API (¡Corregido a /sync!)
            - id: football-api-service
              uri: lb://servicio-football-api
              predicates:
                - Path=/api/sync/**

            # 10. Microservicio Posiciones
            - id: posiciones-service
              uri: lb://servicio-posiciones
              predicates:
                - Path=/api/posiciones/**

            # 11. Microservicio Usuarios
            - id: usuarios-service
              uri: lb://servicio-usuarios
              predicates:
                - Path=/api/usuarios/**

            # 12. Microservicio Partidos
            - id: partidos-service
              uri: lb://servicio-partidos
              predicates:
                - Path=/api/partidos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway