server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/bd_lesiones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=system-system-system-system-system-1234