# Nombre de la aplicacion durante pruebas.
<<<<<<< HEAD
spring.application.name=servicio-lesiones-test
 
# Base de datos en memoria H2. Se crea al iniciar las pruebas y desaparece al terminar.
spring.datasource.url=jdbc:h2:mem:lesionesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
=======
<<<<<<< HEAD
spring.application.name=servicio-jugadores-test
 
# Base de datos en memoria H2. Se crea al iniciar las pruebas y desaparece al terminar.
spring.datasource.url=jdbc:h2:mem:jugadoresdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
=======
spring.application.name=servicio-ligas-test
 
# Base de datos en memoria H2. Se crea al iniciar las pruebas y desaparece al terminar.
spring.datasource.url=jdbc:h2:mem:ligasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
>>>>>>> 0be4bd329a9b4e87cfb4dab2233d764e14c4f93c
>>>>>>> 35fd69e62755442a4e4842371606df94780c2052
 
# Driver JDBC de H2.
spring.datasource.driver-class-name=org.h2.Driver
 
# Usuario por defecto de H2.
spring.datasource.username=sa
 
# Password vacia para H2.
spring.datasource.password=
 
# Hibernate crea las tablas al iniciar y las elimina al cerrar el contexto.
spring.jpa.hibernate.ddl-auto=create-drop
 
# Muestra SQL en consola para entender que consultas ejecuta JPA.
spring.jpa.show-sql=true
 
# Evita consultas JPA fuera de la capa service durante la serializacion.
spring.jpa.open-in-view=false
 
# Clave secreta de prueba para el filtro JWT.
jwt.secret=system-system-system-system-system-1234
 
# Opcional: desactiva Swagger en pruebas si no lo necesitas.
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
