spring.application.name=servicio-usuarios
server.port=8091

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://bd-mysql:3306/bd_usuarios?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:system}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET:system-system-system-system-system-1234}

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/