server.port=8092
spring.application.name=servicio-football-api

spring.datasource.url=jdbc:mysql://localhost:3306/bd_football_api?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de la API Externa (API-Football)
api.football.url=https://v3.football.api-sports.io
api.football.key=9bbd4d4e8b7736d8705b7267e8ae9afb

jwt.secret=system-system-system-system-system-1234

# Documentacion Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
