server.port=8090
spring.application.name=servicio-auth

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

<<<<<<< HEAD
=======
spring.datasource.url=jdbc:mysql://localhost:3306/bd_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=21999288-2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

>>>>>>> 00384755d7d4fa3093b0f1d952b4d7af320b4aec
usuarios.url=http://servicio-usuarios:8091

jwt.secret=system-system-system-system-system-1234

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

eureka.client.service-url.defaultZone=http://servidor-eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true