<<<<<<< HEAD
spring.application.name=servicio-lesiones
=======
<<<<<<< HEAD
spring.application.name=servicio-jugadores
=======
spring.application.name=servicio-ligas

>>>>>>> 0be4bd329a9b4e87cfb4dab2233d764e14c4f93c
>>>>>>> 35fd69e62755442a4e4842371606df94780c2052
spring.profiles.active=dev