spring.application.name=servicio-lesiones
server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://bd-mysql:3306/bd_lesiones?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:system}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET:system-system-system-system-system-1234}

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

jugadores.api.url=http://servicio-jugadores:8083

spring.main.allow-bean-definition-overriding=true