<<<<<<< HEAD
spring.application.name=servicio-posiciones 

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

spring.datasource.url=jdbc:mysql://localhost:3306/bd_posiciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8089

jwt.secret=system-system-system-system-system-1234
=======
spring.profiles.active=dev
>>>>>>> 3faa15e0f03c396faff37cabae10204e1dc10b22
